#!/usr/bin/env python


def multitone(cls):
    instances = {}
    print 'cls:', cls
    def classwrapper(*args, **kwargs):
        if cls.__name__ not in instances:
            instances[cls.__name__] = cls(*args, **kwargs)

        return instances[cls.__name__]
    print 'instances:', instances
    return classwrapper


@multitone
class MyClass(object):

    def __init__(self, first=None, second=None):
        assert(first is not None)
        assert(second is not None)





a = MyClass('first', 'second')
b = MyClass('first', 'second')

print a, b

print a is b
